name: MSBuild

on: 
  push:
    tags:
    - '*'

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

jobs:
  build:
    runs-on: windows-2022
      
    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x86 ${{env.SOLUTION_FILE_PATH}}

    - name: Compress-Archive x86
      run: powershell Compress-Archive -Path "Release/version.dll" -DestinationPath "x86.zip"

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 ${{env.SOLUTION_FILE_PATH}}

    - name: Compress-Archive x64
      run: powershell Compress-Archive -Path "x64/Release/version.dll" -DestinationPath "x64.zip"

    - name: Create a Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "x86.zip, x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
